//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_3layer1.UI.Students {
    
    public partial class CourseRegistration {
        
        protected global::System.Web.UI.WebControls.DropDownList ddlSubjects;
        
        protected global::System.Web.UI.WebControls.TextBox txtSemester;
        
        protected global::System.Web.UI.WebControls.Button btnRegister;
        
        protected global::System.Web.UI.WebControls.GridView gvRegistrations;
        
        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        protected global::System.Web.UI.WebControls.Button btnBack;
    }
}
