//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_3layer1.UI.Students {
    
    public partial class ViewGrades {
        
        protected global::System.Web.UI.WebControls.GridView gvGrades;
        
        protected global::System.Web.UI.WebControls.Button btnBack;
    }
}
